# NOTE: update this with your service name
service: care-app

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-dynamodb-local
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

custom:
  stage: ${opt:stage,self:provider.stage}
  memberTableName: '${self:custom.stage}-members'
  workerTableName: '${self:custom.stage}-workers'
  dynamodb:
    start:
       migrate: true
    stages:
        - dev

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  environment:
    memberTableName: ${self:custom.memberTableName}
    workerTableName: ${self:custom.workerTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ MemberTable, Arn]
        - "Fn::GetAtt": [ WorkerTable, Arn]

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

resources:
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/api-gateway-errors.yml)}
